import { useCallback, useRef } from "react";
import type { Dispatch, MutableRefObject } from "react";
import type { ConversationItem, RateLimitSnapshot, TurnPlan } from "@/types";
import { interruptTurn as interruptTurnService } from "@services/tauri";
import { buildItemsFromTurn, getThreadTimestamp } from "@utils/threadItems";
import {
  asString,
  normalizePlanUpdate,
  normalizeRateLimits,
  normalizeTokenUsage,
} from "@threads/utils/threadNormalize";
import { looksAutoGeneratedThreadName } from "@threads/utils/threadNaming";
import {
  getParentThreadIdFromThread,
  isSubagentThreadSource,
  shouldHideSubagentThreadFromSidebar,
} from "@threads/utils/threadRpc";
import type { ThreadAction } from "./useThreadsReducer";

type UseThreadTurnEventsOptions = {
  dispatch: Dispatch<ThreadAction>;
  planByThreadRef: MutableRefObject<Record<string, TurnPlan | null>>;
  getCurrentRateLimits?: (workspaceId: string) => RateLimitSnapshot | null;
  getCustomName: (workspaceId: string, threadId: string) => string | undefined;
  isThreadHidden: (workspaceId: string, threadId: string) => boolean;
  setThreadLoaded: (threadId: string, isLoaded: boolean) => void;
  markProcessing: (threadId: string, isProcessing: boolean) => void;
  markReviewing: (threadId: string, isReviewing: boolean) => void;
  setActiveTurnId: (threadId: string, turnId: string | null) => void;
  getActiveTurnId: (threadId: string) => string | null;
  pendingInterruptsRef: MutableRefObject<Set<string>>;
  pushThreadErrorMessage: (threadId: string, message: string) => void;
  safeMessageActivity: () => void;
  recordThreadActivity: (workspaceId: string, threadId: string, timestamp?: number) => void;
};

function normalizeThreadStatusType(status: Record<string, unknown>): string {
  const typeRaw = status.type ?? status.statusType ?? status.status_type;
  if (typeof typeRaw !== "string") {
    return "";
  }
  return typeRaw
    .trim()
    .toLowerCase()
    .replace(/[\s_-]/g, "");
}

function getTurnTimestamp(turn: Record<string, unknown>) {
  const raw =
    (turn.completedAt ??
      turn.completed_at ??
      turn.updatedAt ??
      turn.updated_at ??
      turn.startedAt ??
      turn.started_at ??
      turn.createdAt ??
      turn.created_at) ??
    null;
  if (typeof raw === "number" && Number.isFinite(raw)) {
    return raw;
  }
  if (typeof raw === "string") {
    const parsed = Date.parse(raw);
    if (Number.isFinite(parsed)) {
      return parsed;
    }
    const numeric = Number(raw);
    if (Number.isFinite(numeric)) {
      return numeric;
    }
  }
  return Date.now();
}

export function useThreadTurnEvents({
  dispatch,
  planByThreadRef,
  getCurrentRateLimits,
  getCustomName,
  isThreadHidden,
  setThreadLoaded,
  markProcessing,
  markReviewing,
  setActiveTurnId,
  getActiveTurnId,
  pendingInterruptsRef,
  pushThreadErrorMessage,
  safeMessageActivity,
  recordThreadActivity,
}: UseThreadTurnEventsOptions) {
  const immediateActiveTurnIdByThreadRef = useRef<Record<string, string | null>>({});
  const lastReducerActiveTurnIdByThreadRef = useRef<Record<string, string | null>>({});
  const hasOptimisticActiveTurnByThreadRef = useRef<Record<string, boolean>>({});

  const getLatestKnownActiveTurnId = useCallback(
    (threadId: string) => {
      const reducerTurnId = getActiveTurnId(threadId);
      const lastReducerTurnId = lastReducerActiveTurnIdByThreadRef.current[threadId];
      const immediateTurnId = immediateActiveTurnIdByThreadRef.current[threadId];
      const hasOptimisticTurn =
        hasOptimisticActiveTurnByThreadRef.current[threadId] === true;

      if (hasOptimisticTurn && immediateTurnId !== undefined) {
        if (reducerTurnId === immediateTurnId) {
          // Reducer caught up with our optimistic write.
          hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
        } else if (
          lastReducerTurnId !== undefined &&
          reducerTurnId !== lastReducerTurnId
        ) {
          // Reducer changed independently (e.g. resume hydration), so adopt it.
          hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
          immediateActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
        } else {
          lastReducerActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
          return immediateTurnId;
        }
      }

      if (lastReducerTurnId !== reducerTurnId) {
        // Keep cache aligned with reducer when we are not in an optimistic window.
        lastReducerActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
        immediateActiveTurnIdByThreadRef.current[threadId] = reducerTurnId;
      }

      if (immediateTurnId !== undefined) {
        return immediateActiveTurnIdByThreadRef.current[threadId];
      }
      return reducerTurnId;
    },
    [getActiveTurnId],
  );

  const shouldClearCompletedPlan = useCallback((threadId: string, turnId: string) => {
    const plan = planByThreadRef.current[threadId];
    if (!plan || plan.steps.length === 0) {
      return false;
    }
    if (turnId && plan.turnId !== turnId) {
      return false;
    }
    return plan.steps.every((step) => step.status === "completed");
  }, [planByThreadRef]);

  const hydrateTurnSnapshot = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turn: Record<string, unknown> | undefined,
    ) => {
      if (!turn) {
        return;
      }
      const items = buildItemsFromTurn(turn);
      if (items.length === 0) {
        return;
      }
      const hasCustomName = Boolean(getCustomName(workspaceId, threadId));
      items.forEach((item) => {
        dispatch({
          type: "upsertItem",
          workspaceId,
          threadId,
          item,
          hasCustomName,
        });
      });

      const latestAssistantMessage = [...items]
        .reverse()
        .find(
          (item): item is ConversationItem & { kind: "message"; role: "assistant" } =>
            item.kind === "message" && item.role === "assistant",
        );
      const timestamp = getTurnTimestamp(turn);
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp,
      });
      recordThreadActivity(workspaceId, threadId, timestamp);
      if (latestAssistantMessage?.text) {
        dispatch({
          type: "setLastAgentMessage",
          threadId,
          text: latestAssistantMessage.text,
          timestamp,
        });
      }
      safeMessageActivity();
    },
    [dispatch, getCustomName, recordThreadActivity, safeMessageActivity],
  );

  const onThreadStarted = useCallback(
    (workspaceId: string, thread: Record<string, unknown>) => {
      const threadId = asString(thread.id);
      if (!threadId) {
        return;
      }
      if (isThreadHidden(workspaceId, threadId)) {
        return;
      }
      if (shouldHideSubagentThreadFromSidebar(thread.source)) {
        dispatch({ type: "hideThread", workspaceId, threadId });
        return;
      }
      const sourceParentId = getParentThreadIdFromThread(thread);
      if (isSubagentThreadSource(thread.source) && !sourceParentId) {
        // Some thread/started payloads omit parent metadata initially.
        // Ignore these until richer data (for example thread/list) can link safely.
        return;
      }
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const timestamp = getThreadTimestamp(thread);
      const activityTimestamp = timestamp > 0 ? timestamp : Date.now();
      recordThreadActivity(workspaceId, threadId, activityTimestamp);
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp: activityTimestamp,
      });

      const customName = getCustomName(workspaceId, threadId);
      if (!customName) {
        const preview = asString(thread.preview).trim();
        if (preview) {
          const name = preview.length > 38 ? `${preview.slice(0, 38)}…` : preview;
          dispatch({ type: "setThreadName", workspaceId, threadId, name });
        }
      }
      safeMessageActivity();
    },
    [dispatch, getCustomName, isThreadHidden, recordThreadActivity, safeMessageActivity],
  );

  const onThreadNameUpdated = useCallback(
    (
      workspaceId: string,
      payload: { threadId: string; threadName: string | null },
    ) => {
      const { threadId, threadName } = payload;
      if (!threadId || !threadName) {
        return;
      }
      const normalizedThreadId = threadId.trim().toLowerCase();
      const normalizedThreadName = threadName.trim();
      if (
        normalizedThreadName.toLowerCase() === normalizedThreadId &&
        looksAutoGeneratedThreadName(normalizedThreadName)
      ) {
        return;
      }
      if (getCustomName(workspaceId, threadId)) {
        return;
      }
      dispatch({
        type: "setThreadName",
        workspaceId,
        threadId,
        name: normalizedThreadName,
      });
    },
    [dispatch, getCustomName],
  );

  const onThreadArchived = useCallback(
    (workspaceId: string, threadId: string) => {
      if (!threadId) {
        return;
      }
      dispatch({ type: "hideThread", workspaceId, threadId });
    },
    [dispatch],
  );

  const onThreadUnarchived = useCallback(
    (workspaceId: string, threadId: string) => {
      if (!threadId) {
        return;
      }
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const customName = getCustomName(workspaceId, threadId);
      if (customName) {
        dispatch({
          type: "setThreadName",
          workspaceId,
          threadId,
          name: customName,
        });
      }
      const timestamp = Date.now();
      dispatch({
        type: "setThreadTimestamp",
        workspaceId,
        threadId,
        timestamp,
      });
      recordThreadActivity(workspaceId, threadId, timestamp);
      safeMessageActivity();
    },
    [dispatch, getCustomName, recordThreadActivity, safeMessageActivity],
  );

  const onTurnStarted = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      turn?: Record<string, unknown>,
    ) => {
      dispatch({
        type: "ensureThread",
        workspaceId,
        threadId,
      });
      hydrateTurnSnapshot(workspaceId, threadId, turn);
      if (pendingInterruptsRef.current.has(threadId)) {
        pendingInterruptsRef.current.delete(threadId);
        if (turnId) {
          void interruptTurnService(workspaceId, threadId, turnId).catch(() => {});
        }
        return;
      }
      markProcessing(threadId, true);
      if (turnId) {
        lastReducerActiveTurnIdByThreadRef.current[threadId] =
          getActiveTurnId(threadId);
        hasOptimisticActiveTurnByThreadRef.current[threadId] = true;
        immediateActiveTurnIdByThreadRef.current[threadId] = turnId;
        setActiveTurnId(threadId, turnId);
      }
    },
    [
      dispatch,
      getActiveTurnId,
      hydrateTurnSnapshot,
      markProcessing,
      pendingInterruptsRef,
      setActiveTurnId,
    ],
  );

  const onTurnCompleted = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      turn?: Record<string, unknown>,
    ) => {
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      if (turnId && activeTurnId && turnId !== activeTurnId) {
        return;
      }
      dispatch({
        type: "ensureThread",
        workspaceId,
        threadId,
      });
      hydrateTurnSnapshot(workspaceId, threadId, turn);
      markProcessing(threadId, false);
      hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
      immediateActiveTurnIdByThreadRef.current[threadId] = null;
      setActiveTurnId(threadId, null);
      pendingInterruptsRef.current.delete(threadId);
      if (shouldClearCompletedPlan(threadId, turnId)) {
        dispatch({ type: "clearThreadPlan", threadId });
      }
    },
    [
      dispatch,
      getLatestKnownActiveTurnId,
      hydrateTurnSnapshot,
      markProcessing,
      pendingInterruptsRef,
      setActiveTurnId,
      shouldClearCompletedPlan,
    ],
  );

  const onThreadStatusChanged = useCallback(
    (_workspaceId: string, threadId: string, status: Record<string, unknown>) => {
      const statusType = normalizeThreadStatusType(status);
      if (!statusType) {
        return;
      }
      if (statusType === "active") {
        markProcessing(threadId, true);
        return;
      }
      if (
        statusType === "idle" ||
        statusType === "notloaded" ||
        statusType === "systemerror"
      ) {
        markProcessing(threadId, false);
        if (statusType === "notloaded") {
          setThreadLoaded(threadId, false);
          markReviewing(threadId, false);
        }
        hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
        immediateActiveTurnIdByThreadRef.current[threadId] = null;
        setActiveTurnId(threadId, null);
        pendingInterruptsRef.current.delete(threadId);
      }
    },
    [
      markProcessing,
      markReviewing,
      pendingInterruptsRef,
      setActiveTurnId,
      setThreadLoaded,
    ],
  );

  const onThreadClosed = useCallback(
    (_workspaceId: string, threadId: string) => {
      setThreadLoaded(threadId, false);
      markProcessing(threadId, false);
      markReviewing(threadId, false);
      hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
      immediateActiveTurnIdByThreadRef.current[threadId] = null;
      setActiveTurnId(threadId, null);
      pendingInterruptsRef.current.delete(threadId);
    },
    [
      markProcessing,
      markReviewing,
      pendingInterruptsRef,
      setActiveTurnId,
      setThreadLoaded,
    ],
  );

  const onTurnPlanUpdated = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      payload: { explanation: unknown; plan: unknown },
    ) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      const normalized = normalizePlanUpdate(
        turnId,
        payload.explanation,
        payload.plan,
      );
      dispatch({ type: "setThreadPlan", threadId, plan: normalized });
    },
    [dispatch],
  );

  const onTurnDiffUpdated = useCallback(
    (workspaceId: string, threadId: string, diff: string) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      dispatch({ type: "setThreadTurnDiff", threadId, diff });
    },
    [dispatch],
  );

  const onThreadTokenUsageUpdated = useCallback(
    (
      workspaceId: string,
      threadId: string,
      tokenUsage: Record<string, unknown> | null,
    ) => {
      dispatch({ type: "ensureThread", workspaceId, threadId });
      dispatch({
        type: "setThreadTokenUsage",
        threadId,
        tokenUsage: normalizeTokenUsage(tokenUsage),
      });
    },
    [dispatch],
  );

  const onAccountRateLimitsUpdated = useCallback(
    (workspaceId: string, rateLimits: Record<string, unknown>) => {
      const previousRateLimits = getCurrentRateLimits?.(workspaceId) ?? null;
      dispatch({
        type: "setRateLimits",
        workspaceId,
        rateLimits: normalizeRateLimits(rateLimits, previousRateLimits),
      });
    },
    [dispatch, getCurrentRateLimits],
  );

  const onTurnError = useCallback(
    (
      workspaceId: string,
      threadId: string,
      turnId: string,
      payload: { message: string; willRetry: boolean },
    ) => {
      if (payload.willRetry) {
        return;
      }
      const activeTurnId = getLatestKnownActiveTurnId(threadId);
      if (turnId && activeTurnId && turnId !== activeTurnId) {
        return;
      }
      dispatch({ type: "ensureThread", workspaceId, threadId });
      markProcessing(threadId, false);
      markReviewing(threadId, false);
      hasOptimisticActiveTurnByThreadRef.current[threadId] = false;
      immediateActiveTurnIdByThreadRef.current[threadId] = null;
      setActiveTurnId(threadId, null);
      const message = payload.message
        ? `Turn failed: ${payload.message}`
        : "Turn failed.";
      pushThreadErrorMessage(threadId, message);
      safeMessageActivity();
    },
    [
      dispatch,
      getLatestKnownActiveTurnId,
      markProcessing,
      markReviewing,
      pushThreadErrorMessage,
      safeMessageActivity,
      setActiveTurnId,
    ],
  );

  return {
    onThreadStarted,
    onThreadNameUpdated,
    onThreadArchived,
    onThreadUnarchived,
    onTurnStarted,
    onTurnCompleted,
    onThreadStatusChanged,
    onThreadClosed,
    onTurnPlanUpdated,
    onTurnDiffUpdated,
    onThreadTokenUsageUpdated,
    onAccountRateLimitsUpdated,
    onTurnError,
  };
}
